### ISSUE TITLE
Inquiry about the new model

### ISSUE THREAD

**Issue by YiweiJiang2015** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#41]
hi, I notice that a new model has shown up in the leaderboard named "Value-Agnostic Conversational Semantic Parsing". Is there any publication linked to the model?

**Comment by eaplatanios** [comment]
Hi! Yes there is a paper that will be presented at ACL this summer. We shall post here when it's made available online (which should be sooner than that).

**Comment by eaplatanios** [comment]
We just posted the paper here: [https://www.microsoft.com/en-us/research/publication/value-agnostic-conversational-semantic-parsing/](https://www.microsoft.com/en-us/research/publication/value-agnostic-conversational-semantic-parsing/).
