### ISSUE TITLE
What is the different between SMCalFlow 1.0 and 2.0?

### ISSUE THREAD

**Issue by PosoSAgapo** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#60]
Hi, thank you for your contribution of the datasets.  I noticed that there is SMCalFlow 1.0 and SMCalFlow 2.0 in this repository, but this is not mentioned in either your paper or your leader board, which only contains SMCalFlow.  If possible, may you explain the difference between SMCalFlow 1.0 and SMCalFlow 2.0?

**Comment by YiweiJiang2015** [comment]
If my understanding is correct, version 1.0 has been deprecated in the leaderboard where model scores are evaluated against version 1.1. The major difference between 1.1 and 2.0 is that the latter deduces type hints (e.g. ^(Event), ^(Constraint)) for each function call within a program.

**Comment by PosoSAgapo** [comment]
> If my understanding is correct, version 1.0 has been deprecated in the leaderboard where model scores are now evaluated against version 1.1. The major difference between 1.1 and 2.0 is that the latter deduces type hints (e.g. ^(Event), ^(Constraint)) for each function call within a program.

Thank you for your information ;)
