### ISSUE TITLE
program length

### ISSUE THREAD

**Issue by jrmmrn** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#64]
Hello,

 Looking at your paper (Task-Oriented Dialogue as Dataflow Synthesis), there is a table with program length for .25, .50, .75 quantiles (table 1) - with values (11, 40, 57) for SMCalflow.
This looks on the hight side... How is this length calculated?
for example - what is the length of this program. (which looks to be of "average" length):
(Yield
  :output (CreateCommitEventWrapper
    :event (CreatePreflightEventWrapper :constraint (Constraint[Event]
      :start (?= 
        (DateAtTimeWithDefaults
         :date (Tomorrow) 
         :time (NumberAM
            :number #(Number 10.0)))) 
      :subject (?= #(String "soccer game")))))) 

Thanks!

**Comment by sammthomson** [comment]
48. Parentheses, hashes, and double quotes are all separate tokens in our linearization.

```python
from dataflow.core.lispress import parse_lispress
from dataflow.core.linearize import lispress_to_seq

a = """(Yield
:output (CreateCommitEventWrapper
:event (CreatePreflightEventWrapper :constraint (Constraint[Event]
:start (?=
(DateAtTimeWithDefaults
:date (Tomorrow)
:time (NumberAM
:number #(Number 10.0))))
:subject (?= #(String "soccer game"))))))"""
seq = lispress_to_seq(parse_lispress(a))
# ['(', 'Yield', ':output', '(', 'CreateCommitEventWrapper', ':event', '(', 'CreatePreflightEventWrapper', ':constraint', '(', 'Constraint[Event]', ':start', '(', '?=', '(', 'DateAtTimeWithDefaults', ':date', '(', 'Tomorrow', ')', ':time', '(', 'NumberAM', ':number', '#', '(', 'Number', '10.0', ')', ')', ')', ')', ':subject', '(', '?=', '#', '(', 'String', '"', 'soccer', 'game', '"', ')', ')', ')', ')', ')', ')']
len(seq)
# 48
```

**Comment by jrmmrn** [comment]
I see...

So that's the expression length, right?

In the table description it actually says:
For programs, “Length” is the number of function calls

Thanks!

**Comment by sammthomson** [comment]
Yeah, it's the length of the target sequence of the seq2seq model. Just reran on the SMCalFlow train set to verify, and got `(11,37,56)` for `(p25,p50,p75)`, which is about right. So the table caption is slightly inaccurate, at least for SMCalFlow.

**Comment by jrmmrn** [comment]
Thanks a lot for taking the time to verify!
