### ISSUE TITLE
how to get the string of program as in the paper instead of lispress

### ISSUE THREAD

**Issue by zqwerty** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#70]
I've read the relevant issues and READMEs. The annotation of the program is in the lispress format, which can be parsed through `parse_lispress` and transformed to a `Program` object through `lispress_to_program`. However, how can I get the string that represents the function calls directly as in the paper (e.g., `findEvent(EventSpec(start=DateTimeSpec(month=feb, day=30)))`)?

Thanks!

**Comment by sammthomson** [comment]
Hi @zqwerty, we have not publicly released any code yet that renders or parses that format. The idea for the data/code release was to use a Lisp-like format to keep parsing and rendering as simple as possible.

**Comment by zqwerty** [comment]
Thank you for your quick response!
